# Review of Python Basics

Original tutorial developed by DePaul University (CSC 478) - revised by Dr. Jie Tao.

## Basic Calculations

Basic arithmetic calculations:

In [1]:
x = 1 + 2 * 3
x

7

Other calculations:

In [2]:
y = 2 ** 3
y

8

Logic Calculation:

In [3]:
x == y

False

String Calculation:

In [4]:
my_str = 'Fairfield' + 'University'
print(my_str)

FairfieldUniversity


In [5]:
my_str.upper()

'FAIRFIELDUNIVERSITY'

In [6]:
my_str.lower()

'fairfielduniversity'

In [7]:
my_str

'FairfieldUniversity'

Notice that upper() and lower() are methods - they do not change the variable value.

In [8]:
len(my_str)

19

## Data Types

In [9]:
a = 2 + 3
b = a * 4
c = b - 7
L = [a,b,c]
print(L)

[5, 20, 13]


In [10]:
M = [10, 2, "a", 3.5]
N = L + M
print(N)

[5, 20, 13, 10, 2, 'a', 3.5]


In [11]:
len(N)

7

Lists + Dicts:

In [12]:
# This is what a comment looks like 
fruits = ['apples','oranges','pears','bananas']
for fruit in fruits:
    print (fruit + ' for sale')

fruitPrices = {'apples': 2.00, 'oranges': 1.50, 'pears': 1.75}
for fruit, price in fruitPrices.items():
    if price < 2.00:
        print ('%s cost %f a pound' % (fruit, price))
    else:
        print (fruit + ' are too expensive!')

apples for sale
oranges for sale
pears for sale
bananas for sale
apples are too expensive!
oranges cost 1.500000 a pound
pears cost 1.750000 a pound


In [13]:
# Example of python's list comprehension construction:

nums = [1,2,3,4,5,6]
plusOneNums = [x+1 for x in nums]
print ("plusOneNums =", plusOneNums)
oddNums = [x for x in nums if x % 2 == 1]
print ("oddNums = ", oddNums)
oddNumsPlusOne = [x+1 for x in nums if x % 2 ==1]
print ("oddNumsPlusOne = ", oddNumsPlusOne)

plusOneNums = [2, 3, 4, 5, 6, 7]
oddNums =  [1, 3, 5]
oddNumsPlusOne =  [2, 4, 6]


Dictionaries:

In [14]:
# Dictionaries

studentIds = {'knuth': 42.0, 'turing': 56.0, 'nash': 92.0 }
studentIds['turing']

56.0

In [15]:
studentIds['ada'] = 97.0
studentIds

{'knuth': 42.0, 'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [16]:
del studentIds['knuth']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [17]:
studentIds['knuth'] = [42.0,'forty-two']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0, 'knuth': [42.0, 'forty-two']}

In [18]:
studentIds.keys()

dict_keys(['turing', 'nash', 'ada', 'knuth'])

In [19]:
studentIds.values()

dict_values([56.0, 92.0, 97.0, [42.0, 'forty-two']])

In [20]:
studentIds.items()

dict_items([('turing', 56.0), ('nash', 92.0), ('ada', 97.0), ('knuth', [42.0, 'forty-two'])])

In [21]:
len(studentIds) 

4

## Numpy Basics

In [22]:
import numpy as np

In [23]:
# Creating a 1-d array

my_arr = np.array([1,2,3,4,5])
my_arr

array([1, 2, 3, 4, 5])

In [24]:
# Creating a 1-d array from an existing Python list

my_lst = [1, 2, 3, 4, 5, 6]

my_arr = np.array(my_lst)
my_arr

array([1, 2, 3, 4, 5, 6])

In [25]:
my_arr/5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [26]:
another_arr = np.array([2, 3, 4, 5, 6, 7])

my_res = my_lst * another_arr
my_res

array([ 2,  6, 12, 20, 30, 42])

In [27]:
my_res.sum()

112

In [28]:
my_res.mean()

18.666666666666668

In [29]:
# Dot product of two vectors

np.dot(my_lst, another_arr)

112

In [30]:
# Creating a 2-d array

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# Transpose a 2-d array

X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
# Array slicing

X[1,2]

6

In [33]:
X[0,:]

array([1, 2, 3])

In [34]:
X[1:,1:]

array([[5, 6],
       [8, 9]])

In [35]:
X[1:,0:2]

array([[4, 5],
       [7, 8]])

In [36]:
# Using arrays to index into other arrays (e.g., Boolean masks)

A = np.array([1, 2, 3, 4, 5, 6])

A > 3

array([False, False, False,  True,  True,  True])

In [37]:
A[A > 3]

array([4, 5, 6])

In [38]:
sum(A[A > 3])

15

In [39]:
Ind = (A > 1) & (A < 6)
print(Ind)
A[Ind]

[False  True  True  True  True False]


array([2, 3, 4, 5])